### ISSUE TITLE
NPE on some devices on getContext() in TeamFragment

### ISSUE THREAD

**Issue by hybrezz54** [hybrezz54/OnTheProwl-Android#1]
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.technowolves.ontheprowl/org.technowolves.ontheprowl.view.activity.MainActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1956)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3351)
    at android.app.ActivityThread.access$700(ActivityThread.java:123)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1151)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4424)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:371)
    at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:366)
    at org.technowolves.ontheprowl.view.fragment.TeamFragment.getFileName(TeamFragment.java:201)
    at org.technowolves.ontheprowl.view.fragment.TeamFragment.onListItemClick(TeamFragment.java:155)
    at org.technowolves.ontheprowl.view.activity.MainActivity.onListItemClick(MainActivity.java:146)
    at org.technowolves.ontheprowl.view.fragment.MainFragment.addTeamsFromStorage(MainFragment.java:156)
    at org.technowolves.ontheprowl.view.fragment.MainFragment.onCreateView(MainFragment.java:60)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
    at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:174)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:598)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1133)
    at android.app.Activity.performStart(Activity.java:4475)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1929)
    ... 12 more

**Comment by hybrezz54** [comment]
Fixed in V1.4 & apk version 1.1
